project_id = "play-the-legend"

[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322
major_version = 17

[auth]
enabled = true
site_url = "http://localhost:3105"
additional_redirect_urls = ["http://localhost:3105"]

[auth.email]
enable_signup = true
enable_confirmations = false
